baseURL = "http://anrepo.github.io/"
languageCode = "ru"
# Выбор Языка по умолчанию
defaultContentLanguage = "ru"
title = "Profile Project"
theme = "template-theme"
# theme = "bootstrap-theme"

# false - добавит запись с версией Hugo первой строкой в тег <head>
# например, такую: '<meta name="generator" content="Hugo 0.67.1" />'
disableHugoGeneratorInject = true


[markup]
    # Goldmark - это библиотека Hugo для использования языка разметки "Markdown"
    [markup.goldmark]
        [markup.goldmark.renderer]
            # unsafe - со значением "true" позвоняет использовать html и javascript в файлах с расширением *.md (Markdown)
            # по умолчанию unsafe = false
            unsafe = true


copyright = 'Everything is mine'
defaultContentLanguageInSubdir = "true"
# Отключение неиспользуемых языков (полезно при работе над переводом)
disableLanguages = ["ar", "fr"]
[languages]
    [languages.ru]
        languageName = 'Russian'
        contentDir = 'content/ru'
        title = 'Блог'
        weight = 1
    [languages.en]
        languageName = 'English'
        contentDir = 'content/en'
        title = 'My blog'
        weight = 2
    # Арабский введен для демонстрации использования
    # правостороннего написания языка
    [languages.ar]
        languagedirection = 'rtl'
        languageName = 'ar'
        contentDir = 'content/ar'
        title = 'مقالات'
        weight = 3
    [languages.fr]
        languageName = 'fr'
        contentDir = 'content/fr'
        title = 'My blog'
        weight = 4
    [params]
        [params.navigation]
            help = 'Help'